import { Button, VerticalBox , LineEdit} from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<string> results: "Hello";
    in-out property<string> label: "Quote";
    in-out property <bool> open-curtain;
    callback divide-income(string);
    callback income-edited(string);
    property <int> space: 40;
    property <bool> income-is-empty: false;
    animate background { duration: 800ms; }
    
    background: #313e50;
    GridLayout {
        spacing: (space / 2) * 1px;
        padding: (space) * 1px;
        Row {
            Text {
                font-size: 22px;
                font-weight: 900;
                horizontal-alignment: center;
                // vertical-alignment: center;
                color: gray;
                text: "\{root.label}";
            }
        }
        Row {
            Text {
                font-size: 20px;
                font-weight: 700;
                horizontal-alignment: center;
                vertical-alignment: center;
                text: "Enter your income";
            }
        }
        Row {
            VerticalBox {
                padding: 0;
                income := LineEdit {
                    // width: parent.width;
                    // height: parent.height;
                    horizontal-alignment: center;
                    placeholder-text: "Enter your number";
                    height: 35px;
                    font-size: 20px;
                    edited => {
                        root.open-curtain = false;
                        root.income-is-empty = false;
                    }
                }
                if root.income-is-empty : Text {
                    text: "Please fill up the value";
                    color: #f55c5c;
                    
                }
            }
        }
        Row {
            Button {
                text: "Calculate";
                primary: true;
                height: 35px;
                clicked => {
                    if ( income.text != "") { 
                        root.income-is-empty = false;
                        root.open-curtain = true;
                        root.divide-income(income.text)
                    } else {
                        root.income-is-empty = true;
                    }
                }
            }
        }
        Row {

            VerticalBox {
                Rectangle {
                    background: #f2f2f2;
                    height: 100px;
                    Text {
                        color:black;
                        horizontal-alignment: center;
                        text: root.results;
                    }
                    // Left curtain
                    Rectangle {
                        background: #333333;
                        x: 0px;
                        width: open-curtain ? 0px : (parent.width / 2);
                        height: parent.height;
                        animate width { duration: 250ms; easing: ease-in; }
                    }

                    // Right curtain
                    Rectangle {
                        background: #333333;
                        x: open-curtain ? parent.width : (parent.width / 2);
                        width: open-curtain ? 0px : (parent.width / 2);
                        height: parent.height;
                        animate width { duration: 250ms; easing: ease-in; }
                        animate x { duration: 250ms; easing: ease-in; }
                    }
                }
            }
        }
    }
}
